"""
    My Data My Consent - Developer API

    Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@mydatamyconsent.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from com.mydatamyconsent.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from com.mydatamyconsent.exceptions import ApiAttributeError


def lazy_import():
    from com.mydatamyconsent.model.application_user import ApplicationUser
    from com.mydatamyconsent.model.country import Country
    from com.mydatamyconsent.model.document_provider_category import DocumentProviderCategory
    from com.mydatamyconsent.model.organization_address import OrganizationAddress
    from com.mydatamyconsent.model.organization_category import OrganizationCategory
    from com.mydatamyconsent.model.organization_financial_account import OrganizationFinancialAccount
    from com.mydatamyconsent.model.organization_kyo_document import OrganizationKyoDocument
    from com.mydatamyconsent.model.organization_meta_data import OrganizationMetaData
    from com.mydatamyconsent.model.organization_status import OrganizationStatus
    from com.mydatamyconsent.model.organization_type import OrganizationType
    globals()['ApplicationUser'] = ApplicationUser
    globals()['Country'] = Country
    globals()['DocumentProviderCategory'] = DocumentProviderCategory
    globals()['OrganizationAddress'] = OrganizationAddress
    globals()['OrganizationCategory'] = OrganizationCategory
    globals()['OrganizationFinancialAccount'] = OrganizationFinancialAccount
    globals()['OrganizationKyoDocument'] = OrganizationKyoDocument
    globals()['OrganizationMetaData'] = OrganizationMetaData
    globals()['OrganizationStatus'] = OrganizationStatus
    globals()['OrganizationType'] = OrganizationType


class Organization(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'created_by': (str,),  # noqa: E501
            'created_at_utc': (datetime,),  # noqa: E501
            'updated_by': (str, none_type,),  # noqa: E501
            'updated_at_utc': (datetime, none_type,),  # noqa: E501
            'created_by_user': (ApplicationUser,),  # noqa: E501
            'updated_by_user': (ApplicationUser,),  # noqa: E501
            'deleted_by': (str, none_type,),  # noqa: E501
            'deleted_at_utc': (datetime, none_type,),  # noqa: E501
            'deleted_by_user': (ApplicationUser,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'data_partner_id': (str, none_type,),  # noqa: E501
            'type_id': (str,),  # noqa: E501
            'category_id': (str,),  # noqa: E501
            'document_provider_category_id': (str, none_type,),  # noqa: E501
            'name': (str, none_type,),  # noqa: E501
            'regulator_name': (str, none_type,),  # noqa: E501
            'brand_name': (str, none_type,),  # noqa: E501
            'authorized_personnel_tax_id': (str, none_type,),  # noqa: E501
            'authorized_personnel_name': (str, none_type,),  # noqa: E501
            'registration_id': (str, none_type,),  # noqa: E501
            'vat_id': (str, none_type,),  # noqa: E501
            'tax_id': (str, none_type,),  # noqa: E501
            'description': (str, none_type,),  # noqa: E501
            'logo_url': (str, none_type,),  # noqa: E501
            'contact_email': (str, none_type,),  # noqa: E501
            'phone_number': (str, none_type,),  # noqa: E501
            'country_id': (str,),  # noqa: E501
            'state_id': (str,),  # noqa: E501
            'status': (OrganizationStatus,),  # noqa: E501
            'company_code': (str, none_type,),  # noqa: E501
            'privacy_policy_url': (str, none_type,),  # noqa: E501
            'terms_of_service_url': (str, none_type,),  # noqa: E501
            'website_url': (str, none_type,),  # noqa: E501
            'is_government_organization': (bool,),  # noqa: E501
            'dl_api_key': (str, none_type,),  # noqa: E501
            'is_kyo_completed': (bool,),  # noqa: E501
            'is_enabled': (bool,),  # noqa: E501
            'is_data_provider': (bool,),  # noqa: E501
            'is_data_consumer': (bool,),  # noqa: E501
            'submitted_at_utc': (datetime, none_type,),  # noqa: E501
            'approved_by': (str, none_type,),  # noqa: E501
            'approved_at_utc': (datetime, none_type,),  # noqa: E501
            'is_digi_locker_organization': (bool,),  # noqa: E501
            'is_mdmc_maintained': (bool,),  # noqa: E501
            'is_bbps': (bool,),  # noqa: E501
            'meta_data': (OrganizationMetaData,),  # noqa: E501
            'country_code': (str, none_type,),  # noqa: E501
            'organization_type': (OrganizationType,),  # noqa: E501
            'organization_category': (OrganizationCategory,),  # noqa: E501
            'document_provider_category': (DocumentProviderCategory,),  # noqa: E501
            'addresses': ([OrganizationAddress], none_type,),  # noqa: E501
            'financial_accounts': ([OrganizationFinancialAccount], none_type,),  # noqa: E501
            'country_state': (Country,),  # noqa: E501
            'approved_by_user': (ApplicationUser,),  # noqa: E501
            'kyo_documents': ([OrganizationKyoDocument], none_type,),  # noqa: E501
            'is_delete': (bool,),  # noqa: E501
            'recovery_token': (str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'created_by': 'createdBy',  # noqa: E501
        'created_at_utc': 'createdAtUtc',  # noqa: E501
        'updated_by': 'updatedBy',  # noqa: E501
        'updated_at_utc': 'updatedAtUtc',  # noqa: E501
        'created_by_user': 'createdByUser',  # noqa: E501
        'updated_by_user': 'updatedByUser',  # noqa: E501
        'deleted_by': 'deletedBy',  # noqa: E501
        'deleted_at_utc': 'deletedAtUtc',  # noqa: E501
        'deleted_by_user': 'deletedByUser',  # noqa: E501
        'id': 'id',  # noqa: E501
        'data_partner_id': 'dataPartnerId',  # noqa: E501
        'type_id': 'typeId',  # noqa: E501
        'category_id': 'categoryId',  # noqa: E501
        'document_provider_category_id': 'documentProviderCategoryId',  # noqa: E501
        'name': 'name',  # noqa: E501
        'regulator_name': 'regulatorName',  # noqa: E501
        'brand_name': 'brandName',  # noqa: E501
        'authorized_personnel_tax_id': 'authorizedPersonnelTaxId',  # noqa: E501
        'authorized_personnel_name': 'authorizedPersonnelName',  # noqa: E501
        'registration_id': 'registrationId',  # noqa: E501
        'vat_id': 'vatId',  # noqa: E501
        'tax_id': 'taxId',  # noqa: E501
        'description': 'description',  # noqa: E501
        'logo_url': 'logoUrl',  # noqa: E501
        'contact_email': 'contactEmail',  # noqa: E501
        'phone_number': 'phoneNumber',  # noqa: E501
        'country_id': 'countryId',  # noqa: E501
        'state_id': 'stateId',  # noqa: E501
        'status': 'status',  # noqa: E501
        'company_code': 'companyCode',  # noqa: E501
        'privacy_policy_url': 'privacyPolicyUrl',  # noqa: E501
        'terms_of_service_url': 'termsOfServiceUrl',  # noqa: E501
        'website_url': 'websiteUrl',  # noqa: E501
        'is_government_organization': 'isGovernmentOrganization',  # noqa: E501
        'dl_api_key': 'dlApiKey',  # noqa: E501
        'is_kyo_completed': 'isKyoCompleted',  # noqa: E501
        'is_enabled': 'isEnabled',  # noqa: E501
        'is_data_provider': 'isDataProvider',  # noqa: E501
        'is_data_consumer': 'isDataConsumer',  # noqa: E501
        'submitted_at_utc': 'submittedAtUtc',  # noqa: E501
        'approved_by': 'approvedBy',  # noqa: E501
        'approved_at_utc': 'approvedAtUtc',  # noqa: E501
        'is_digi_locker_organization': 'isDigiLockerOrganization',  # noqa: E501
        'is_mdmc_maintained': 'isMdmcMaintained',  # noqa: E501
        'is_bbps': 'isBbps',  # noqa: E501
        'meta_data': 'metaData',  # noqa: E501
        'country_code': 'countryCode',  # noqa: E501
        'organization_type': 'organizationType',  # noqa: E501
        'organization_category': 'organizationCategory',  # noqa: E501
        'document_provider_category': 'documentProviderCategory',  # noqa: E501
        'addresses': 'addresses',  # noqa: E501
        'financial_accounts': 'financialAccounts',  # noqa: E501
        'country_state': 'countryState',  # noqa: E501
        'approved_by_user': 'approvedByUser',  # noqa: E501
        'kyo_documents': 'kyoDocuments',  # noqa: E501
        'is_delete': 'isDelete',  # noqa: E501
        'recovery_token': 'recoveryToken',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Organization - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            created_by (str): [optional]  # noqa: E501
            created_at_utc (datetime): [optional]  # noqa: E501
            updated_by (str, none_type): [optional]  # noqa: E501
            updated_at_utc (datetime, none_type): [optional]  # noqa: E501
            created_by_user (ApplicationUser): [optional]  # noqa: E501
            updated_by_user (ApplicationUser): [optional]  # noqa: E501
            deleted_by (str, none_type): [optional]  # noqa: E501
            deleted_at_utc (datetime, none_type): [optional]  # noqa: E501
            deleted_by_user (ApplicationUser): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            data_partner_id (str, none_type): [optional]  # noqa: E501
            type_id (str): [optional]  # noqa: E501
            category_id (str): [optional]  # noqa: E501
            document_provider_category_id (str, none_type): [optional]  # noqa: E501
            name (str, none_type): [optional]  # noqa: E501
            regulator_name (str, none_type): [optional]  # noqa: E501
            brand_name (str, none_type): [optional]  # noqa: E501
            authorized_personnel_tax_id (str, none_type): [optional]  # noqa: E501
            authorized_personnel_name (str, none_type): [optional]  # noqa: E501
            registration_id (str, none_type): [optional]  # noqa: E501
            vat_id (str, none_type): [optional]  # noqa: E501
            tax_id (str, none_type): [optional]  # noqa: E501
            description (str, none_type): [optional]  # noqa: E501
            logo_url (str, none_type): [optional]  # noqa: E501
            contact_email (str, none_type): [optional]  # noqa: E501
            phone_number (str, none_type): [optional]  # noqa: E501
            country_id (str): [optional]  # noqa: E501
            state_id (str): [optional]  # noqa: E501
            status (OrganizationStatus): [optional]  # noqa: E501
            company_code (str, none_type): [optional]  # noqa: E501
            privacy_policy_url (str, none_type): [optional]  # noqa: E501
            terms_of_service_url (str, none_type): [optional]  # noqa: E501
            website_url (str, none_type): [optional]  # noqa: E501
            is_government_organization (bool): [optional]  # noqa: E501
            dl_api_key (str, none_type): [optional]  # noqa: E501
            is_kyo_completed (bool): [optional]  # noqa: E501
            is_enabled (bool): [optional]  # noqa: E501
            is_data_provider (bool): [optional]  # noqa: E501
            is_data_consumer (bool): [optional]  # noqa: E501
            submitted_at_utc (datetime, none_type): [optional]  # noqa: E501
            approved_by (str, none_type): [optional]  # noqa: E501
            approved_at_utc (datetime, none_type): [optional]  # noqa: E501
            is_digi_locker_organization (bool): [optional]  # noqa: E501
            is_mdmc_maintained (bool): [optional]  # noqa: E501
            is_bbps (bool): [optional]  # noqa: E501
            meta_data (OrganizationMetaData): [optional]  # noqa: E501
            country_code (str, none_type): [optional]  # noqa: E501
            organization_type (OrganizationType): [optional]  # noqa: E501
            organization_category (OrganizationCategory): [optional]  # noqa: E501
            document_provider_category (DocumentProviderCategory): [optional]  # noqa: E501
            addresses ([OrganizationAddress], none_type): [optional]  # noqa: E501
            financial_accounts ([OrganizationFinancialAccount], none_type): [optional]  # noqa: E501
            country_state (Country): [optional]  # noqa: E501
            approved_by_user (ApplicationUser): [optional]  # noqa: E501
            kyo_documents ([OrganizationKyoDocument], none_type): [optional]  # noqa: E501
            is_delete (bool): [optional]  # noqa: E501
            recovery_token (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Organization - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            created_by (str): [optional]  # noqa: E501
            created_at_utc (datetime): [optional]  # noqa: E501
            updated_by (str, none_type): [optional]  # noqa: E501
            updated_at_utc (datetime, none_type): [optional]  # noqa: E501
            created_by_user (ApplicationUser): [optional]  # noqa: E501
            updated_by_user (ApplicationUser): [optional]  # noqa: E501
            deleted_by (str, none_type): [optional]  # noqa: E501
            deleted_at_utc (datetime, none_type): [optional]  # noqa: E501
            deleted_by_user (ApplicationUser): [optional]  # noqa: E501
            id (str): [optional]  # noqa: E501
            data_partner_id (str, none_type): [optional]  # noqa: E501
            type_id (str): [optional]  # noqa: E501
            category_id (str): [optional]  # noqa: E501
            document_provider_category_id (str, none_type): [optional]  # noqa: E501
            name (str, none_type): [optional]  # noqa: E501
            regulator_name (str, none_type): [optional]  # noqa: E501
            brand_name (str, none_type): [optional]  # noqa: E501
            authorized_personnel_tax_id (str, none_type): [optional]  # noqa: E501
            authorized_personnel_name (str, none_type): [optional]  # noqa: E501
            registration_id (str, none_type): [optional]  # noqa: E501
            vat_id (str, none_type): [optional]  # noqa: E501
            tax_id (str, none_type): [optional]  # noqa: E501
            description (str, none_type): [optional]  # noqa: E501
            logo_url (str, none_type): [optional]  # noqa: E501
            contact_email (str, none_type): [optional]  # noqa: E501
            phone_number (str, none_type): [optional]  # noqa: E501
            country_id (str): [optional]  # noqa: E501
            state_id (str): [optional]  # noqa: E501
            status (OrganizationStatus): [optional]  # noqa: E501
            company_code (str, none_type): [optional]  # noqa: E501
            privacy_policy_url (str, none_type): [optional]  # noqa: E501
            terms_of_service_url (str, none_type): [optional]  # noqa: E501
            website_url (str, none_type): [optional]  # noqa: E501
            is_government_organization (bool): [optional]  # noqa: E501
            dl_api_key (str, none_type): [optional]  # noqa: E501
            is_kyo_completed (bool): [optional]  # noqa: E501
            is_enabled (bool): [optional]  # noqa: E501
            is_data_provider (bool): [optional]  # noqa: E501
            is_data_consumer (bool): [optional]  # noqa: E501
            submitted_at_utc (datetime, none_type): [optional]  # noqa: E501
            approved_by (str, none_type): [optional]  # noqa: E501
            approved_at_utc (datetime, none_type): [optional]  # noqa: E501
            is_digi_locker_organization (bool): [optional]  # noqa: E501
            is_mdmc_maintained (bool): [optional]  # noqa: E501
            is_bbps (bool): [optional]  # noqa: E501
            meta_data (OrganizationMetaData): [optional]  # noqa: E501
            country_code (str, none_type): [optional]  # noqa: E501
            organization_type (OrganizationType): [optional]  # noqa: E501
            organization_category (OrganizationCategory): [optional]  # noqa: E501
            document_provider_category (DocumentProviderCategory): [optional]  # noqa: E501
            addresses ([OrganizationAddress], none_type): [optional]  # noqa: E501
            financial_accounts ([OrganizationFinancialAccount], none_type): [optional]  # noqa: E501
            country_state (Country): [optional]  # noqa: E501
            approved_by_user (ApplicationUser): [optional]  # noqa: E501
            kyo_documents ([OrganizationKyoDocument], none_type): [optional]  # noqa: E501
            is_delete (bool): [optional]  # noqa: E501
            recovery_token (str, none_type): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
